//! Hook registration macros.
//!
//! [`hook!`] and [`async_hook!`] for registering event lifecycle observers.
//!
//! Note: The `__hook_extract!` and `__async_hook_extract!` macros are now
//! auto-generated by `evildoer_macro::define_events!` in `hooks.rs`.

/// Define a hook and register it in the [`HOOKS`](crate::hooks::HOOKS) slice.
///
/// # Example
///
/// ```ignore
/// hook!(log_open, BufferOpen, 100, "Log buffer opens", |ctx| {
///     if let HookContext::BufferOpen { path, .. } = ctx {
///         tracing::info!(path = %path.display(), "Opened buffer");
///     }
/// });
/// ```
#[macro_export]
macro_rules! hook {
	($name:ident, $event:ident, $priority:expr, $desc:expr, mutable |$ctx:ident| $body:expr) => {
		paste::paste! {
			#[allow(clippy::unused_unit)]
			fn [<hook_handler_ $name>](
				$ctx: &mut $crate::hooks::MutableHookContext,
			) -> $crate::hooks::HookAction {
				let result = { $body };
				::core::convert::Into::into(result)
			}

			#[allow(non_upper_case_globals)]
			#[linkme::distributed_slice($crate::hooks::HOOKS)]
			static [<HOOK_ $name>]: $crate::hooks::HookDef = $crate::hooks::HookDef {
				id: concat!(env!("CARGO_PKG_NAME"), "::", stringify!($name)),
				name: stringify!($name),
				event: $crate::hooks::HookEvent::$event,
				description: $desc,
				priority: $priority,
				mutability: $crate::hooks::HookMutability::Mutable,
				handler: $crate::hooks::HookHandler::Mutable([<hook_handler_ $name>]),
				source: $crate::RegistrySource::Crate(env!("CARGO_PKG_NAME")),
			};
		}
	};
	($name:ident, $event:ident, $priority:expr, $desc:expr, |$($param:ident : $ty:ty),*| $body:expr) => {
		$crate::hook!($name, $event, $priority, $desc, |ctx| {
			$crate::__hook_extract!($event, ctx, $($param : $ty),*);
			$body
		});
	};
	($name:ident, $event:ident, $priority:expr, $desc:expr, |$ctx:ident| $body:expr) => {
		paste::paste! {
			#[allow(clippy::unused_unit)]
			fn [<hook_handler_ $name>]($ctx: &$crate::hooks::HookContext) -> $crate::hooks::HookAction {
				let result = { $body };
				::core::convert::Into::into(result)
			}

			#[allow(non_upper_case_globals)]
			#[linkme::distributed_slice($crate::hooks::HOOKS)]
			static [<HOOK_ $name>]: $crate::hooks::HookDef = $crate::hooks::HookDef {
				id: concat!(env!("CARGO_PKG_NAME"), "::", stringify!($name)),
				name: stringify!($name),
				event: $crate::hooks::HookEvent::$event,
				description: $desc,
				priority: $priority,
				mutability: $crate::hooks::HookMutability::Immutable,
				handler: $crate::hooks::HookHandler::Immutable([<hook_handler_ $name>]),
				source: $crate::RegistrySource::Crate(env!("CARGO_PKG_NAME")),
			};
		}
	};
}

/// Defines an async hook that owns extracted parameters.
#[macro_export]
macro_rules! async_hook {
	($name:ident, $event:ident, $priority:expr, $desc:expr, setup |$ctx:ident| { $($setup:tt)* } async || $body:expr) => {
		$crate::hook!($name, $event, $priority, $desc, |$ctx| {
			$($setup)*
			let owned = $ctx.to_owned();
			$crate::hooks::HookAction::Async(::std::boxed::Box::pin(async move {
				$crate::__async_hook_extract!($event, owned);
				let result = { $body };
				::core::convert::Into::into(result)
			}))
		});
	};
	($name:ident, $event:ident, $priority:expr, $desc:expr, async || $body:expr) => {
		$crate::hook!($name, $event, $priority, $desc, |ctx| {
			let owned = ctx.to_owned();
			$crate::hooks::HookAction::Async(::std::boxed::Box::pin(async move {
				$crate::__async_hook_extract!($event, owned);
				let result = { $body };
				::core::convert::Into::into(result)
			}))
		});
	};
	($name:ident, $event:ident, $priority:expr, $desc:expr, setup |$ctx:ident| { $($setup:tt)* } async |$($param:ident : $ty:ty),*| $body:expr) => {
		$crate::hook!($name, $event, $priority, $desc, |$ctx| {
			$($setup)*
			let owned = $ctx.to_owned();
			$crate::hooks::HookAction::Async(::std::boxed::Box::pin(async move {
				$crate::__async_hook_extract!($event, owned, $($param : $ty),*);
				let result = { $body };
				::core::convert::Into::into(result)
			}))
		});
	};
	($name:ident, $event:ident, $priority:expr, $desc:expr, async |$($param:ident : $ty:ty),*| $body:expr) => {
		$crate::hook!($name, $event, $priority, $desc, |ctx| {
			let owned = ctx.to_owned();
			$crate::hooks::HookAction::Async(::std::boxed::Box::pin(async move {
				$crate::__async_hook_extract!($event, owned, $($param : $ty),*);
				let result = { $body };
				::core::convert::Into::into(result)
			}))
		});
	};
}
