#ifndef KAK_FFI_H
#define KAK_FFI_H

/* Auto-generated by cbindgen. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * FNV-1a hash function.
 *
 * Matches Kakoune's `fnv1a` implementation in hash.hh.
 */
uintptr_t fnv1a(const uint8_t *data, uintptr_t len);

/**
 * MurmurHash3 (32-bit) hash function.
 *
 * Matches Kakoune's `murmur3` implementation in hash.cc.
 * Based on <https://github.com/PeterScott/murmur3>
 */
uintptr_t murmur3(const uint8_t *input, uintptr_t len);

/**
 * Combine two hash values.
 *
 * Matches Kakoune's `combine_hash` implementation in hash.hh.
 */
uintptr_t combine_hash(uintptr_t lhs, uintptr_t rhs);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* KAK_FFI_H */
